=== raml-apis/AccuWeather/schemas/city-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "object",
  "properties": {
    "Version": {
      "required": false,
      "type": "integer"
    },
    "Key": {
      "required": false,
      "type": "string"
    },
    "Type": {
      "required": false,
      "type": "string"
    },
    "Rank": {
      "required": false,
      "type": "integer"
    },
    "LocalizedName": {
      "required": false,
      "type": "string"
    },
    "EnglishName": {
      "required": false,
      "type": "string"
    },
    "PrimaryPostalCode": {
      "required": false,
      "type": "string"
    },
    "Region": {
      "required": false,
      "type": "object",
      "properties": {
        "ID": {
          "required": false,
          "type": "string"
        },
        "LocalizedName": {
          "required": false,
          "type": "string"
        },
        "EnglishName": {
          "required": false,
          "type": "string"
        }
      }
    },
    "Country": {
      "required": false,
      "type": "object",
      "properties": {
        "ID": {
          "required": false,
          "type": "string"
        },
        "LocalizedName": {
          "required": false,
          "type": "string"
        },
        "EnglishName": {
          "required": false,
          "type": "string"
        }
      }
    },
    "AdministrativeArea": {
      "required": false,
      "type": "object",
      "properties": {
        "ID": {
          "required": false,
          "type": "string"
        },
        "LocalizedName": {
          "required": false,
          "type": "string"
        },
        "EnglishName": {
          "required": false,
          "type": "string"
        },
        "Level": {
          "required": false,
          "type": "integer"
        },
        "LocalizedType": {
          "required": false,
          "type": "string"
        },
        "EnglishType": {
          "required": false,
          "type": "string"
        },
        "CountryID": {
          "required": false,
          "type": "string"
        }
      }
    },
    "TimeZone": {
      "required": false,
      "type": "object",
      "properties": {
        "Code": {
          "required": false,
          "type": "string"
        },
        "Name": {
          "required": false,
          "type": "string"
        },
        "GmtOffset": {
          "required": false,
          "type": "integer"
        },
        "IsDaylightSaving": {
          "required": false,
          "type": "boolean"
        },
        "NextOffsetChange": {
          "required": false,
          "type": "string"
        }
      }
    },
    "GeoPosition": {
      "required": false,
      "type": "object",
      "properties": {
        "Latitude": {
          "required": false,
          "type": "number"
        },
        "Longitude": {
          "required": false,
          "type": "number"
        },
        "Elevation": {
          "required": false,
          "type": "object",
          "properties": {
            "Metric": {
              "required": false,
              "type": "object",
              "properties": {
                "Value": {
                  "required": false,
                  "type": "number"
                },
                "Unit": {
                  "required": false,
                  "type": "string"
                }
              }
            },
            "Imperial": {
              "required": false,
              "type": "object",
              "properties": {
                "Value": {
                  "required": false,
                  "type": "integer"
                },
                "Unit": {
                  "required": false,
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "IsAlias": {
      "required": false,
      "type": "boolean"
    },
    "SupplementalAdminAreas": {
      "required": false,
      "type": "array",
      "items": {
        "required": false,
        "type": "object",
        "properties": {
          "EnglishName": {
            "required": false,
            "type": "string"
          },
          "Level": {
            "required": false,
            "type": "integer"
          },
          "LocalizedName": {
            "required": false,
            "type": "string"
          }
        }
      }
    }
  }
}

=== raml-apis/AccuWeather/examples/city-example.json
{
    "Version": 1,
    "Key": "335315",
    "Type": "City",
    "Rank": 55,
    "LocalizedName": "State College",
    "EnglishName": "State College",
    "PrimaryPostalCode": "16801",
    "Region": 
    {
        "ID": "NAM",
        "LocalizedName": "North America",
        "EnglishName": "North America"
    },
    "Country": 
    {
        "ID": "US",
        "LocalizedName": "United States",
        "EnglishName": "United States"
    },
    "AdministrativeArea": 
    {
        "ID": "PA",
        "LocalizedName": "Pennsylvania",
        "EnglishName": "Pennsylvania",
        "Level": 1,
        "LocalizedType": "State",
        "EnglishType": "State",
        "CountryID": "US"
    },
    "TimeZone": 
    {
        "Code": "EDT",
        "Name": "America/New_York",
        "GmtOffset": -4,
        "IsDaylightSaving": true,
        "NextOffsetChange": "2012-11-04T06:00:00Z"
    },
    "GeoPosition": 
    {
        "Latitude": 40.79,
        "Longitude": -77.86,
        "Elevation": 
        {
            "Metric": 
            {
                "Value": 366.4,
                "Unit": "m"
            },
            "Imperial": 
            {
                "Value": 1202,
                "Unit": "ft"
            }
        }
    },
    "IsAlias": false,
    "SupplementalAdminAreas": [
        {
            "Level": 2,
            "LocalizedName": "Centre",
            "EnglishName": "Centre"
        }
    ]
}

=== raml-apis/AccuWeather/examples/cityNeighbors-example.json
[
  {
    "Version" : 1 ,
    "Key" : "133695" ,
    "Type" : "City" ,
    "Rank" : 53 ,
    "LocalizedName" : "Montrouge" ,
    "EnglishName" : "Montrouge" ,
    "PrimaryPostalCode" : "" ,
    "Region" : {
      "ID" : "EUR" ,
      "LocalizedName" : "Europe" ,
      "EnglishName" : "Europe"
    } ,
    "Country" : {
      "ID" : "FR" ,
      "LocalizedName" : "France" ,
      "EnglishName" : "France"
    } ,
    "AdministrativeArea" : {
      "ID" : "92" ,
      "LocalizedName" : "Seine Heights" ,
      "EnglishName" : "Seine Heights" ,
      "Level" : 1 ,
      "LocalizedType" : "Department" ,
      "EnglishType" : "Department" ,
      "CountryID" : "FR"
    } ,
    "TimeZone" : {
      "Code" : "CET" ,
      "Name" : "Europe/Paris" ,
      "GmtOffset" : 1 ,
      "IsDaylightSaving" : false ,
      "NextOffsetChange" : "2014-03-30T01:00:00Z"
    } ,
    "GeoPosition" : {
      "Latitude" : 48.82 ,
      "Longitude" : 2.32 ,
      "Elevation" : {
        "Metric" : {
          "Value" : 76 ,
          "Unit" : "m" ,
          "UnitType" : 5
        } ,
        "Imperial" : {
          "Value" : 249 ,
          "Unit" : "ft" ,
          "UnitType" : 0
        }
      }
    } ,
    "IsAlias" : false ,
    "SupplementalAdminAreas" : [
      {
        "Level" : 2 ,
        "LocalizedName" : "Antony" ,
        "EnglishName" : "Antony"
      }
    ]
  } , {
    "Version" : 1 ,
    "Key" : "133599" ,
    "Type" : "City" ,
    "Rank" : 53 ,
    "LocalizedName" : "Bagnolet" ,
    "EnglishName" : "Bagnolet" ,
    "PrimaryPostalCode" : "" ,
    "Region" : {
      "ID" : "EUR" ,
      "LocalizedName" : "Europe" ,
      "EnglishName" : "Europe"
    } ,
    "Country" : {
      "ID" : "FR" ,
      "LocalizedName" : "France" ,
      "EnglishName" : "France"
    } ,
    "AdministrativeArea" : {
      "ID" : "93" ,
      "LocalizedName" : "Seine-Saint-Denis" ,
      "EnglishName" : "Seine-Saint-Denis" ,
      "Level" : 1 ,
      "LocalizedType" : "Department" ,
      "EnglishType" : "Department" ,
      "CountryID" : "FR"
    } ,
    "TimeZone" : {
      "Code" : "CET" ,
      "Name" : "Europe/Paris" ,
      "GmtOffset" : 1 ,
      "IsDaylightSaving" : false ,
      "NextOffsetChange" : "2014-03-30T01:00:00Z"
    } ,
    "GeoPosition" : {
      "Latitude" : 48.87 ,
      "Longitude" : 2.42 ,
      "Elevation" : {
        "Metric" : {
          "Value" : 109 ,
          "Unit" : "m" ,
          "UnitType" : 5
        } ,
        "Imperial" : {
          "Value" : 358 ,
          "Unit" : "ft" ,
          "UnitType" : 0
        }
      }
    } ,
    "IsAlias" : false ,
    "SupplementalAdminAreas" : [
      {
        "Level" : 2 ,
        "LocalizedName" : "Bobigny" ,
        "EnglishName" : "Bobigny"
      }
    ]
  }
]
