=== raml-apis/AccuWeather/schemas/cityListAutocomplete-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "array" ,
  "items" : 
    {
      "type" : "object" ,
      "properties" : {
        "Version" : {
          "type" : "number" ,
          "required" : false
        } ,
        "Key" : {
          "type" : "string" ,
          "required" : false
        } ,
        "Type" : {
          "type" : "string" ,
          "required" : false
        } ,
        "Rank" : {
          "type" : "number" ,
          "required" : false
        } ,
        "LocalizedName" : {
          "type" : "string" ,
          "required" : false
        } ,
        "Country" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "ID" : {
              "type" : "string" ,
              "required" : false
            } ,
            "LocalizedName" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } ,
        "AdministrativeArea" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "ID" : {
              "type" : "string" ,
              "required" : false
            } ,
            "LocalizedName" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      }
    }
  
}

=== raml-apis/AccuWeather/examples/cityListAutocomplete-example.json
[
  {
    "Version" : 1 ,
    "Key" : "349727" ,
    "Type" : "City" ,
    "Rank" : 15 ,
    "LocalizedName" : "Nueva York" ,
    "Country" : {
      "ID" : "US" ,
      "LocalizedName" : "Estados Unidos"
    } ,
    "AdministrativeArea" : {
      "ID" : "NY" ,
      "LocalizedName" : "Nueva York"
    }
  } , {
    "Version" : 1 ,
    "Key" : "187745" ,
    "Type" : "City" ,
    "Rank" : 30 ,
    "LocalizedName" : "Nueva Delhi" ,
    "Country" : {
      "ID" : "IN" ,
      "LocalizedName" : "India"
    } ,
    "AdministrativeArea" : {
      "ID" : "DL" ,
      "LocalizedName" : "Delhi"
    }
  } , {
    "Version" : 1 ,
    "Key" : "35547" ,
    "Type" : "City" ,
    "Rank" : 35 ,
    "LocalizedName" : "Nueva Iguaz" ,
    "Country" : {
      "ID" : "BR" ,
      "LocalizedName" : "Brasil"
    } ,
    "AdministrativeArea" : {
      "ID" : "RJ" ,
      "LocalizedName" : ""
    }
  } , {
    "Version" : 1 ,
    "Key" : "235983" ,
    "Type" : "City" ,
    "Rank" : 35 ,
    "LocalizedName" : "Nuevo Laredo" ,
    "Country" : {
      "ID" : "MX" ,
      "LocalizedName" : "Mexico"
    } ,
    "AdministrativeArea" : {
      "ID" : "TAM" ,
      "LocalizedName" : "Tamaulipas"
    }
  } , {
    "Version" : 1 ,
    "Key" : "348585" ,
    "Type" : "City" ,
    "Rank" : 35 ,
    "LocalizedName" : "Nueva Orleans" ,
    "Country" : {
      "ID" : "US" ,
      "LocalizedName" : "Estados Unidos"
    } ,
    "AdministrativeArea" : {
      "ID" : "LA" ,
      "LocalizedName" : "Luisiana"
    }
  } , {
    "Version" : 1 ,
    "Key" : "128723" ,
    "Type" : "City" ,
    "Rank" : 41 ,
    "LocalizedName" : "Nueva San Salvador" ,
    "Country" : {
      "ID" : "SV" ,
      "LocalizedName" : "El Salvador"
    } ,
    "AdministrativeArea" : {
      "ID" : "LI" ,
      "LocalizedName" : "La Libertad"
    }
  } , {
    "Version" : 1 ,
    "Key" : "118543" ,
    "Type" : "City" ,
    "Rank" : 51 ,
    "LocalizedName" : "Nueva Gerona" ,
    "Country" : {
      "ID" : "CU" ,
      "LocalizedName" : "Cuba"
    } ,
    "AdministrativeArea" : {
      "ID" : "99" ,
      "LocalizedName" : "Isla de la Juventud"
    }
  } , {
    "Version" : 1 ,
    "Key" : "7423" ,
    "Type" : "City" ,
    "Rank" : 55 ,
    "LocalizedName" : "Nueve de Julio" ,
    "Country" : {
      "ID" : "AR" ,
      "LocalizedName" : "Argentina"
    } ,
    "AdministrativeArea" : {
      "ID" : "B" ,
      "LocalizedName" : "Buenos Aires"
    }
  } , {
    "Version" : 1 ,
    "Key" : "116945" ,
    "Type" : "City" ,
    "Rank" : 55 ,
    "LocalizedName" : "Nuevitas" ,
    "Country" : {
      "ID" : "CU" ,
      "LocalizedName" : "Cuba"
    } ,
    "AdministrativeArea" : {
      "ID" : "09" ,
      "LocalizedName" : "Camaguey"
    }
  } , {
    "Version" : 1 ,
    "Key" : "232146" ,
    "Type" : "City" ,
    "Rank" : 55 ,
    "LocalizedName" : "Nuevo Casas Grandes" ,
    "Country" : {
      "ID" : "MX" ,
      "LocalizedName" : "Mexico"
    } ,
    "AdministrativeArea" : {
      "ID" : "CHH" ,
      "LocalizedName" : "Chihuahua"
    }
  }
]
