=== raml-apis/AccuWeather/schemas/forecast-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "array" ,
  "items" : 
    {
      "type" : "object" ,
      "properties" : {
        "DateTime" : {
          "type" : "string" ,
          "required" : false
        } ,
        "EpochDateTime" : {
          "type" : "number" ,
          "required" : false
        } ,
        "WeatherIcon" : {
          "type" : "number" ,
          "required" : false
        } ,
        "IconPhrase" : {
          "type" : "string" ,
          "required" : false
        } ,
        "Temperature" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "Value" : {
              "type" : "number" ,
              "required" : false
            } ,
            "Unit" : {
              "type" : "string" ,
              "required" : false
            } ,
            "UnitType" : {
              "type" : "number" ,
              "required" : false
            }
          }
        } ,
        "PrecipitationProbability" : {
          "type" : "number" ,
          "required" : false
        } ,
        "MobileLink" : {
          "type" : "string" ,
          "required" : false
        } ,
        "Link" : {
          "type" : "string" ,
          "required" : false
        }
      }
    }
  
}

=== raml-apis/AccuWeather/examples/forecast-example.json
[
  {
    "DateTime" : "2013-01-18T15:00:00-05:00" ,
    "EpochDateTime" : 1358539200 ,
    "WeatherIcon" : 1 ,
    "IconPhrase" : "Sunny" ,
    "Temperature" : {
      "Value" : 27 ,
      "Unit" : "F" ,
      "UnitType" : 18
    } ,
    "PrecipitationProbability" : 0 ,
    "MobileLink" : "http://m.accuweather.com/en/us/state-college-pa/16801/hourly-weather-forecast/335315?lang=en-us?hbhhour=15" ,
    "Link" : "http://www.accuweather.com/en/us/state-college-pa/16801/hourly-weather-forecast/335315?lang=en-us?hbhhour=15"
  }
]
