=== raml-apis/AccuWeather/schemas/images-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "MobileLink" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Link" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Radar" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "Size" : {
          "type" : "string" ,
          "required" : false
        } ,
        "Images" : {
          "type" : "array" ,
          "required" : false ,
          "items" : 
            {
              "type" : "object" ,
              "properties" : {
                "Date" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "Url" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            }
          
        }
      }
    } ,
    "Satellite" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "Size" : {
          "type" : "string" ,
          "required" : false
        } ,
        "Images" : {
          "type" : "array" ,
          "required" : false ,
          "items" : 
            {
              "type" : "object" ,
              "properties" : {
                "Date" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "Url" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            }
          
        }
      }
    }
  }
}

=== raml-apis/AccuWeather/examples/images-example.json
{
  "MobileLink" : "http://m.accuweather.com/es/us/pennsylvania/weather-radar" ,
  "Link" : "http://www.accuweather.com/es/us/pennsylvania/weather-radar" ,
  "Radar" : {
    "Size" : "1024x1024" ,
    "Images" : [
      {
        "Date" : "2013-05-16T11:00:00-04:00" ,
        "Url" : "http://vortex.accuweather.com/adc2004/mapspace/usradar/1024x1024/PA__1305161500.png"
      } , {
        "Date" : "2013-05-16T11:05:00-04:00" ,
        "Url" : "http://vortex.accuweather.com/adc2004/mapspace/usradar/1024x1024/PA__1305161505.png"
      } , {
        "Date" : "2013-05-16T11:15:00-04:00" ,
        "Url" : "http://vortex.accuweather.com/adc2004/mapspace/usradar/1024x1024/PA__1305161515.png"
      } , {
        "Date" : "2013-05-16T11:20:00-04:00" ,
        "Url" : "http://vortex.accuweather.com/adc2004/mapspace/usradar/1024x1024/PA__1305161520.png"
      } , {
        "Date" : "2013-05-16T11:35:00-04:00" ,
        "Url" : "http://vortex.accuweather.com/adc2004/mapspace/usradar/1024x1024/PA__1305161535.png"
      }
    ]
  } ,
  "Satellite" : {
    "Size" : "1024x1024" ,
    "Images" : [
      {
        "Date" : "2013-05-16T08:45:00-04:00" ,
        "Url" : "http://vortex.accuweather.com/adc2004/mapspace/world_ir/1024x1024/PA__1305161245.png"
      } , {
        "Date" : "2013-05-16T09:15:00-04:00" ,
        "Url" : "http://vortex.accuweather.com/adc2004/mapspace/world_ir/1024x1024/PA__1305161315.png"
      } , {
        "Date" : "2013-05-16T09:45:00-04:00" ,
        "Url" : "http://vortex.accuweather.com/adc2004/mapspace/world_ir/1024x1024/PA__1305161345.png"
      } , {
        "Date" : "2013-05-16T10:15:00-04:00" ,
        "Url" : "http://vortex.accuweather.com/adc2004/mapspace/world_ir/1024x1024/PA__1305161415.png"
      } , {
        "Date" : "2013-05-16T11:15:00-04:00" ,
        "Url" : "http://vortex.accuweather.com/adc2004/mapspace/world_ir/1024x1024/PA__1305161515.png"
      }
    ]
  }
}
