=== raml-apis/AccuWeather/schemas/phrase-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "EnglishText" : {
      "type" : "string" ,
      "required" : false
    } ,
    "LanguageCode" : {
      "type" : "string" ,
      "required" : false
    } ,
    "PhraseCode" : {
      "type" : "string" ,
      "required" : false
    } ,
    "PhraseId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Text" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/AccuWeather/examples/listSpecificLanguages-example.json
[
  {
    "EnglishText" : "911 Telephone Outage" ,
    "LanguageCode" : "es" ,
    "PhraseCode" : "911TelephoneOutage" ,
    "Text" : "Teléfono en caso de apagones 911"
  } , {
    "EnglishText" : "Menu" ,
    "LanguageCode" : "es" ,
    "PhraseCode" : "Abbr_Menu" ,
    "Text" : "Menú"
  } , {
    "EnglishText" : "About" ,
    "LanguageCode" : "es" ,
    "PhraseCode" : "About" ,
    "Text" : "Acerca de"
  } , {
    "EnglishText" : "Accept" ,
    "LanguageCode" : "es" ,
    "PhraseCode" : "Accept" ,
    "Text" : "Aceptar"
  }
]
