=== raml-apis/AccuWeather/schemas/postalcodes-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "array",
  "items": {
    "required": false,
    "type": "object",
    "properties": {
      "AdministrativeArea": {
        "required": false,
        "type": "object",
        "properties": {
          "ID": {
            "required": false,
            "type": "string"
          },
          "LocalizedName": {
            "required": false,
            "type": "string"
          },
          "EnglishName": {
            "required": false,
            "type": "string"
          },
          "Level": {
            "required": false,
            "type": "integer"
          },
          "LocalizedType": {
            "required": false,
            "type": "string"
          },
          "EnglishType": {
            "required": false,
            "type": "string"
          },
          "CountryID": {
            "required": false,
            "type": "string"
          }
        }
      },
      "Country": {
        "required": false,
        "type": "object",
        "properties": {
          "ID": {
            "required": false,
            "type": "string"
          },
          "LocalizedName": {
            "required": false,
            "type": "string"
          },
          "EnglishName": {
            "required": false,
            "type": "string"
          }
        }
      },
      "EnglishName": {
        "required": false,
        "type": "string"
      },
      "GeoPosition": {
        "required": false,
        "type": "object",
        "properties": {
          "Latitude": {
            "required": false,
            "type": "number"
          },
          "Longitude": {
            "required": false,
            "type": "number"
          },
          "Elevation": {
            "required": false,
            "type": "object",
            "properties": {
              "Metric": {
                "required": false,
                "type": "object",
                "properties": {
                  "Value": {
                    "required": false,
                    "type": "string"
                  },
                  "Unit": {
                    "required": false,
                    "type": "string"
                  },
                  "UnitType": {
                    "required": false,
                    "type": "integer"
                  }
                }
              },
              "Imperial": {
                "required": false,
                "type": "object",
                "properties": {
                  "Value": {
                    "required": false,
                    "type": "string"
                  },
                  "Unit": {
                    "required": false,
                    "type": "string"
                  },
                  "UnitType": {
                    "required": false,
                    "type": "integer"
                  }
                }
              }
            }
          }
        }
      },
      "IsAlias": {
        "required": false,
        "type": "boolean"
      },
      "Key": {
        "required": false,
        "type": "string"
      },
      "LocalizedName": {
        "required": false,
        "type": "string"
      },
      "PrimaryPostalCode": {
        "required": false,
        "type": "string"
      },
      "Rank": {
        "required": false,
        "type": "integer"
      },
      "Region": {
        "required": false,
        "type": "object",
        "properties": {
          "ID": {
            "required": false,
            "type": "string"
          },
          "LocalizedName": {
            "required": false,
            "type": "string"
          },
          "EnglishName": {
            "required": false,
            "type": "string"
          }
        }
      },
      "SupplementalAdminAreas": {
        "required": false,
        "type": "array",
        "items": {
          "required": false,
          "type": "object",
          "properties": {
            "EnglishName": {
              "required": false,
              "type": "string"
            },
            "Level": {
              "required": false,
              "type": "integer"
            },
            "LocalizedName": {
              "required": false,
              "type": "string"
            }
          }
        }
      },
      "TimeZone": {
        "required": false,
        "type": "object",
        "properties": {
          "Code": {
            "required": false,
            "type": "string"
          },
          "Name": {
            "required": false,
            "type": "string"
          },
          "GmtOffset": {
            "required": false,
            "type": "integer"
          },
          "IsDaylightSaving": {
            "required": false,
            "type": "boolean"
          },
          "NextOffsetChange": {
            "required": false,
            "type": "null"
          }
        }
      },
      "Type": {
        "required": false,
        "type": "string"
      },
      "Version": {
        "required": false,
        "type": "integer"
      }
    }
  }
}

=== raml-apis/AccuWeather/examples/cities-example.json
[
  {
    "Version" : 1 ,
    "Key" : "335315" ,
    "Type" : "City" ,
    "Rank" : 55 ,
    "LocalizedName" : "State College" ,
    "EnglishName" : "State College" ,
    "PrimaryPostalCode" : "16801" ,
    "Region" : {
      "ID" : "NAM" ,
      "LocalizedName" : "North America" ,
      "EnglishName" : "North America"
    } ,
    "Country" : {
      "ID" : "US" ,
      "LocalizedName" : "United States" ,
      "EnglishName" : "United States"
    } ,
    "AdministrativeArea" : {
      "ID" : "PA" ,
      "LocalizedName" : "Pennsylvania" ,
      "EnglishName" : "Pennsylvania" ,
      "Level" : 1 ,
      "LocalizedType" : "State" ,
      "EnglishType" : "State" ,
      "CountryID" : "US"
    } ,
    "TimeZone" : {
      "Code" : "EDT" ,
      "Name" : "America/New_York" ,
      "GmtOffset" : -4 ,
      "IsDaylightSaving" : true ,
      "NextOffsetChange" : null
    } ,
    "GeoPosition" : {
      "Latitude" : 40.79 ,
      "Longitude" : -77.86 ,
      "Elevation" : {
        "Metric" : {
          "Value" : "366" ,
          "Unit" : "m" ,
          "UnitType" : 5
        } ,
        "Imperial" : {
          "Value" : "1202" ,
          "Unit" : "ft" ,
          "UnitType" : 0
        }
      }
    } ,
    "IsAlias" : false ,
    "SupplementalAdminAreas" : [
      {
        "Level" : 2 ,
        "LocalizedName" : "Centre" ,
        "EnglishName" : "Centre"
      }
    ]
  } , {
    "Version" : 1 ,
    "Key" : "3-349655_1_AL" ,
    "Type" : "City" ,
    "Rank" : 105 ,
    "LocalizedName" : "State College" ,
    "EnglishName" : "University Park" ,
    "PrimaryPostalCode" : "88003" ,
    "Region" : {
      "ID" : "NAM" ,
      "LocalizedName" : "North America" ,
      "EnglishName" : "North America"
    } ,
    "Country" : {
      "ID" : "US" ,
      "LocalizedName" : "United States" ,
      "EnglishName" : "United States"
    } ,
    "AdministrativeArea" : {
      "ID" : "NM" ,
      "LocalizedName" : "New Mexico" ,
      "EnglishName" : "New Mexico" ,
      "Level" : 1 ,
      "LocalizedType" : "State" ,
      "EnglishType" : "State" ,
      "CountryID" : "US"
    } ,
    "TimeZone" : {
      "Code" : "MDT" ,
      "Name" : "America/Denver" ,
      "GmtOffset" : -6 ,
      "IsDaylightSaving" : true ,
      "NextOffsetChange" : null
    } ,
    "GeoPosition" : {
      "Latitude" : 32.28 ,
      "Longitude" : -106.75 ,
      "Elevation" : {
        "Metric" : {
          "Value" : "1195" ,
          "Unit" : "m" ,
          "UnitType" : 5
        } ,
        "Imperial" : {
          "Value" : "3919" ,
          "Unit" : "ft" ,
          "UnitType" : 0
        }
      }
    } ,
    "IsAlias" : true ,
    "SupplementalAdminAreas" : [
      {
        "Level" : 2 ,
        "LocalizedName" : "Dona Ana" ,
        "EnglishName" : "Dona Ana"
      }
    ]
  } , {
    "Version" : 1 ,
    "Key" : "2153708" ,
    "Type" : "City" ,
    "Rank" : 500 ,
    "LocalizedName" : "State College" ,
    "EnglishName" : "State College" ,
    "PrimaryPostalCode" : "31030" ,
    "Region" : {
      "ID" : "NAM" ,
      "LocalizedName" : "North America" ,
      "EnglishName" : "North America"
    } ,
    "Country" : {
      "ID" : "US" ,
      "LocalizedName" : "United States" ,
      "EnglishName" : "United States"
    } ,
    "AdministrativeArea" : {
      "ID" : "GA" ,
      "LocalizedName" : "Georgia" ,
      "EnglishName" : "Georgia" ,
      "Level" : 1 ,
      "LocalizedType" : "State" ,
      "EnglishType" : "State" ,
      "CountryID" : "US"
    } ,
    "TimeZone" : {
      "Code" : "EDT" ,
      "Name" : "America/New_York" ,
      "GmtOffset" : -4 ,
      "IsDaylightSaving" : true ,
      "NextOffsetChange" : null
    } ,
    "GeoPosition" : {
      "Latitude" : 32.54 ,
      "Longitude" : -83.89 ,
      "Elevation" : {
        "Metric" : {
          "Value" : "160" ,
          "Unit" : "m" ,
          "UnitType" : 5
        } ,
        "Imperial" : {
          "Value" : "524" ,
          "Unit" : "ft" ,
          "UnitType" : 0
        }
      }
    } ,
    "IsAlias" : false ,
    "SupplementalAdminAreas" : [
      {
        "Level" : 2 ,
        "LocalizedName" : "Peach" ,
        "EnglishName" : "Peach"
      }
    ]
  }
]

=== raml-apis/AccuWeather/examples/postalcodes-example.json
[
  {
    "Version" : 1 ,
    "Key" : "37935_PC" ,
    "Type" : "PostalCode" ,
    "Rank" : 55 ,
    "LocalizedName" : "Beverly Hills" ,
    "EnglishName" : "Beverly Hills" ,
    "PrimaryPostalCode" : "90210" ,
    "Region" : {
      "ID" : "NAM" ,
      "LocalizedName" : "North America" ,
      "EnglishName" : "North America"
    } ,
    "Country" : {
      "ID" : "US" ,
      "LocalizedName" : "United States" ,
      "EnglishName" : "United States"
    } ,
    "AdministrativeArea" : {
      "ID" : "CA" ,
      "LocalizedName" : "California" ,
      "EnglishName" : "California" ,
      "Level" : 1 ,
      "LocalizedType" : "State" ,
      "EnglishType" : "State" ,
      "CountryID" : "US"
    } ,
    "TimeZone" : {
      "Code" : "PDT" ,
      "Name" : "America/Los_Angeles" ,
      "GmtOffset" : -7 ,
      "IsDaylightSaving" : true ,
      "NextOffsetChange" : null
    } ,
    "GeoPosition" : {
      "Latitude" : 34.1 ,
      "Longitude" : -118.42 ,
      "Elevation" : {
        "Metric" : {
          "Value" : "244" ,
          "Unit" : "m" ,
          "UnitType" : 5
        } ,
        "Imperial" : {
          "Value" : "800" ,
          "Unit" : "ft" ,
          "UnitType" : 0
        }
      }
    } ,
    "IsAlias" : false ,
    "SupplementalAdminAreas" : [
      {
        "Level" : 2 ,
        "LocalizedName" : "Los Angeles" ,
        "EnglishName" : "Los Angeles"
      }
    ]
  } , {
    "Version" : 1 ,
    "Key" : "407828_PC" ,
    "Type" : "PostalCode" ,
    "Rank" : 500 ,
    "LocalizedName" : "Oulu" ,
    "EnglishName" : "Oulu" ,
    "PrimaryPostalCode" : "90210" ,
    "Region" : {
      "ID" : "EUR" ,
      "LocalizedName" : "Europe" ,
      "EnglishName" : "Europe"
    } ,
    "Country" : {
      "ID" : "FI" ,
      "LocalizedName" : "Finland" ,
      "EnglishName" : "Finland"
    } ,
    "AdministrativeArea" : {
      "ID" : "14" ,
      "LocalizedName" : "Northern Ostrobothnia" ,
      "EnglishName" : "Northern Ostrobothnia" ,
      "Level" : 1 ,
      "LocalizedType" : "Region" ,
      "EnglishType" : "Region" ,
      "CountryID" : "FI"
    } ,
    "TimeZone" : {
      "Code" : "EEST" ,
      "Name" : "Europe/Helsinki" ,
      "GmtOffset" : 3 ,
      "IsDaylightSaving" : true ,
      "NextOffsetChange" : null
    } ,
    "GeoPosition" : {
      "Latitude" : 65.02 ,
      "Longitude" : 25.47 ,
      "Elevation" : {
        "Metric" : {
          "Value" : "0" ,
          "Unit" : "m" ,
          "UnitType" : 5
        } ,
        "Imperial" : {
          "Value" : "0" ,
          "Unit" : "ft" ,
          "UnitType" : 0
        }
      }
    } ,
    "IsAlias" : false ,
    "SupplementalAdminAreas" : [
    ]
  } , {
    "Version" : 1 ,
    "Key" : "236513_PC" ,
    "Type" : "PostalCode" ,
    "Rank" : 500 ,
    "LocalizedName" : "San Mateo Actipan" ,
    "EnglishName" : "San Mateo Actipan" ,
    "PrimaryPostalCode" : "90210" ,
    "Region" : {
      "ID" : "NAM" ,
      "LocalizedName" : "North America" ,
      "EnglishName" : "North America"
    } ,
    "Country" : {
      "ID" : "MX" ,
      "LocalizedName" : "Mexico" ,
      "EnglishName" : "Mexico"
    } ,
    "AdministrativeArea" : {
      "ID" : "TLA" ,
      "LocalizedName" : "Tlaxcala" ,
      "EnglishName" : "Tlaxcala" ,
      "Level" : 1 ,
      "LocalizedType" : "State" ,
      "EnglishType" : "State" ,
      "CountryID" : "MX"
    } ,
    "TimeZone" : {
      "Code" : "CDT" ,
      "Name" : "America/Mexico_City" ,
      "GmtOffset" : -5 ,
      "IsDaylightSaving" : true ,
      "NextOffsetChange" : null
    } ,
    "GeoPosition" : {
      "Latitude" : 19.62 ,
      "Longitude" : -98.6 ,
      "Elevation" : {
        "Metric" : {
          "Value" : "2571" ,
          "Unit" : "m" ,
          "UnitType" : 5
        } ,
        "Imperial" : {
          "Value" : "8436" ,
          "Unit" : "ft" ,
          "UnitType" : 0
        }
      }
    } ,
    "IsAlias" : false ,
    "SupplementalAdminAreas" : [
    ]
  }
]
